'use client'

import { Inter_Tight } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { usePathname } from "next/navigation";

const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const showBanner = pathname !== "/oferta-inmobiliaria";

  return (
    <html lang="en">
      <body
        className={`${interTight.variable} antialiased bg-background-1`}
      >
        <Header />
        {children}
        <Footer showBanner={showBanner} />
      </body>
    </html>
  );
}
